services:
  markitdown-api:
    image: ghcr.io/climactic/markitdown-api:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - DOCS_ENABLED=${DOCS_ENABLED:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
